version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.envs/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0

  worker:
    build: .
    volumes:
      - .:/app
    command: python -m celery -A core worker -l info
    env_file:
      - ./.envs/.env
    depends_on:
      - redis
      - db

  beat:
    build: .
    volumes:
      - .:/app
    command: python -m celery -A core beat
    env_file:
      - ./.envs/.env
    depends_on:
      - redis
      - db

volumes:
  db-data:
